-- F-TAXI ACCOUNTS - CORE PHP DATABASE
CREATE DATABASE IF NOT EXISTS `f_taxi_accounts` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `f_taxi_accounts`;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NULL,
  email_verified_at TIMESTAMP NULL,
  password VARCHAR(255) NOT NULL,
  role ENUM('OWNER','MANAGER') NOT NULL DEFAULT 'MANAGER',
  remember_token VARCHAR(100) NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS drivers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ftaxi_driver_id BIGINT UNSIGNED NULL UNIQUE,
  id_number VARCHAR(50) NULL,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NULL,
  vehicle_number VARCHAR(100) NULL,
  vehicle_name VARCHAR(150) NULL,
  pending_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
  status ENUM('active','inactive') NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS incomes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  driver_id BIGINT UNSIGNED NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  fees_amount DECIMAL(12,2) NULL,
  gst_percentage DECIMAL(5,2) NULL,
  gst_amount DECIMAL(12,2) NULL,
  total_amount DECIMAL(12,2) NULL,
  fees_payment_mode VARCHAR(20) NULL,
  gst_payment_mode VARCHAR(20) NULL,
  fees_upi_id VARCHAR(255) NULL,
  gst_upi_id VARCHAR(255) NULL,
  income_date DATE NULL,
  description VARCHAR(255) NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id),
  KEY idx_income_driver(driver_id),
  CONSTRAINT fk_income_driver FOREIGN KEY(driver_id) REFERENCES drivers(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS expenses (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  expense_name VARCHAR(255) NULL,
  expense_type VARCHAR(255) NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  payment_mode VARCHAR(20) NULL,
  upi_id VARCHAR(255) NULL,
  date DATE NULL,
  expense_date DATE NULL,
  category VARCHAR(100) NULL,
  description VARCHAR(255) NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS advances (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  employee_name VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL DEFAULT 'Salary Advance',
  amount DECIMAL(12,2) NOT NULL,
  payment_mode ENUM('cash','account') NOT NULL,
  upi_id VARCHAR(255) NULL,
  advance_date DATE NOT NULL,
  description VARCHAR(255) NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS daily_accounts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  date DATE NOT NULL UNIQUE,
  opening_balance DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_income DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_expense DECIMAL(12,2) NOT NULL DEFAULT 0,
  closing_balance DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS daily_closings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  closing_date DATE NOT NULL UNIQUE,
  opening_balance DECIMAL(15,2) NOT NULL DEFAULT 0,
  total_income DECIMAL(15,2) NOT NULL DEFAULT 0,
  total_expense DECIMAL(15,2) NOT NULL DEFAULT 0,
  closing_balance DECIMAL(15,2) NOT NULL DEFAULT 0,
  closed_by VARCHAR(255) NULL,
  closed_at TIMESTAMP NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ftaxi_monthly_accounts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  month VARCHAR(20) NOT NULL UNIQUE,
  driver_payout DECIMAL(15,2) NOT NULL DEFAULT 0,
  driver_amt DECIMAL(15,2) NOT NULL DEFAULT 0,
  company_amt DECIMAL(15,2) NOT NULL DEFAULT 0,
  commission DECIMAL(15,2) NOT NULL DEFAULT 0,
  gst DECIMAL(15,2) NOT NULL DEFAULT 0,
  business_commission DECIMAL(15,2) NOT NULL DEFAULT 0,
  pending_amt DECIMAL(15,2) NOT NULL DEFAULT 0,
  amount_paid DECIMAL(15,2) NOT NULL DEFAULT 0,
  advance_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
  toll_fee DECIMAL(15,2) NOT NULL DEFAULT 0,
  service_charge DECIMAL(15,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
) ENGINE=InnoDB;

-- Optional initial accounts. Change these immediately in production.
-- Password for both demo accounts: password
INSERT INTO users (name,username,email,password,role)
SELECT 'Owner','owner','owner@ftaxi.local', '$2y$12$HKG3ZDh3Ar2TtRWKLDDh7OdwgS/QI7DXNlprXnSJl317CzVCl9Q7K', 'OWNER'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username='owner');

INSERT INTO users (name,username,email,password,role)
SELECT 'Manager','manager','manager@ftaxi.local', '$2y$12$HKG3ZDh3Ar2TtRWKLDDh7OdwgS/QI7DXNlprXnSJl317CzVCl9Q7K', 'MANAGER'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username='manager');
