@extends('layouts.app')
@section('content')
<style>
.edit-page{max-width:900px;margin:0 auto}.edit-card{background:#fff;border:1px solid #e5e7eb;border-radius:14px;padding:30px;box-shadow:0 2px 10px rgba(0,0,0,.05)}.field{margin-bottom:20px}.field>label{display:block;margin-bottom:8px;font-weight:600;color:#111827;font-size:14px}.field input,.field textarea,.field select{width:100%;box-sizing:border-box;padding:12px 14px;border:1px solid #d1d5db;border-radius:8px;font-size:14px}.field textarea{min-height:100px;resize:vertical}.payment-options{display:flex;gap:10px;margin-top:8px}.payment-option{display:inline-flex;align-items:center;gap:7px;width:auto;padding:9px 14px;border:1px solid #d1d5db;border-radius:7px;cursor:pointer;font-size:13px;font-weight:500}.payment-option input{width:auto!important;padding:0;margin:0}.payment-option:has(input:checked){border-color:#111827;background:#f3f4f6}.actions{display:flex;gap:10px;margin-top:25px}.btn{padding:12px 20px;border-radius:8px;border:0;text-decoration:none;font-weight:600;cursor:pointer}.btn-primary{background:#111827;color:#fff}.btn-secondary{background:#e5e7eb;color:#111827}.error{color:#dc2626;font-size:13px;margin-top:5px}
</style>
<div class="edit-page"><h2>Edit Expense</h2><p>Update the expense details below.</p><div class="edit-card">
@if($errors->any())<div style="color:#dc2626;margin-bottom:15px;"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form action="{{ route('expenses.update',$expense->id) }}" method="POST">@csrf @method('PUT')
<div class="field"><label for="expense_name">Expense Name</label><input type="text" name="expense_name" id="expense_name" value="{{ old('expense_name',$expense->expense_name) }}" required></div>
<div class="field"><label for="category">Category</label><select name="category" id="category" required><option value="">Select Category</option>@foreach(['Provision','Advertisement','Stationary','Transport','Maintenance','Electricity','Rent','Other'] as $category)<option value="{{ $category }}" {{ old('category',$expense->category)===$category?'selected':'' }}>{{ $category }}</option>@endforeach</select></div>
<div class="field"><label for="amount">Amount</label><input type="number" name="amount" id="amount" step="0.01" min="0" value="{{ old('amount',$expense->amount) }}" required><label style="margin-top:12px;display:block;">Payment Mode</label><div class="payment-options"><label class="payment-option"><input type="radio" name="payment_mode" value="cash" {{ old('payment_mode',$expense->payment_mode ?: 'cash')==='cash'?'checked':'' }} required> Cash</label><label class="payment-option"><input type="radio" name="payment_mode" value="account" {{ old('payment_mode',$expense->payment_mode)==='account'?'checked':'' }}> A/C</label></div></div>
<div class="field" id="upi_id_group" style="display:none;"><label for="upi_id">UPI ID</label><input type="text" name="upi_id" id="upi_id" value="{{ old('upi_id',$expense->upi_id) }}" placeholder="Enter UPI ID manually"></div>
<div class="field"><label for="expense_date">Date</label><input type="date" name="expense_date" id="expense_date" value="{{ old('expense_date',optional($expense->expense_date)->format('Y-m-d') ?? $expense->expense_date) }}" required></div>
<div class="field"><label for="description">Description</label><textarea name="description" id="description">{{ old('description',$expense->description) }}</textarea></div>
<div class="actions"><button class="btn btn-primary" type="submit">Update Expense</button><a class="btn btn-secondary" href="{{ route('expenses.index') }}">Cancel</a></div>
</form></div></div>
<script>
document.addEventListener('DOMContentLoaded',function(){const radios=document.querySelectorAll('input[name="payment_mode"]'),group=document.getElementById('upi_id_group'),upi=document.getElementById('upi_id');function update(){const selected=document.querySelector('input[name="payment_mode"]:checked');if(selected&&selected.value==='account'){group.style.display='block';upi.required=true}else{group.style.display='none';upi.required=false}}radios.forEach(r=>r.addEventListener('change',update));update();});
</script>
@endsection
